#include "MAX98357A.h"
#include "esp_log.h"

esp_err_t MAX98357A_init(const MAX98357A_config_t *config, MAX98357A_handle_t *handle)
{
    ESP_LOGI("MAX98357A", "Initializing MAX98357A");
    ESP_ERROR_CHECK(gpio_set_direction(config->SD_PIN, GPIO_MODE_OUTPUT));
    ESP_ERROR_CHECK(gpio_set_level(config->SD_PIN, 1));

    i2s_chan_handle_t tx_handle;
    i2s_chan_config_t chan_cfg = I2S_CHANNEL_DEFAULT_CONFIG(I2S_NUM_AUTO, I2S_ROLE_MASTER);

    ESP_ERROR_CHECK(i2s_new_channel(&chan_cfg, &tx_handle, NULL));

    /* Setting the configurations, the slot configuration and clock configuration can be generated by the macros
     * These two helper macros are defined in `i2s_std.h` which can only be used in STD mode.
     * They can help to specify the slot and clock configurations for initialization or updating */
    i2s_std_config_t std_cfg = {
        .clk_cfg = I2S_STD_CLK_DEFAULT_CONFIG(MAX98357A_sample_rate),
        .slot_cfg = I2S_STD_MSB_SLOT_DEFAULT_CONFIG(MAX98357A_data_width, I2S_SLOT_MODE_MONO),
        .gpio_cfg = {
            .mclk = I2S_GPIO_UNUSED,
            .bclk = config->BCLK_pin,
            .ws = config->LRCLK_pin,
            .dout = config->DIN_pin,
            .din = I2S_GPIO_UNUSED,
            .invert_flags = {
                .mclk_inv = false,
                .bclk_inv = false,
                .ws_inv = false,
            },
        },
    };

    ESP_ERROR_CHECK(i2s_channel_init_std_mode(tx_handle, &std_cfg));

    ESP_ERROR_CHECK(i2s_channel_enable(tx_handle));

    handle->tx_handle = tx_handle;
    ESP_LOGI("MAX98357A", "MAX98357A initialized");
    return ESP_OK;
}

void MAX98357A_close(MAX98357A_handle_t *handle, const MAX98357A_config_t *config)
{
    gpio_set_level(config->SD_PIN, 0);
    ESP_ERROR_CHECK(i2s_channel_disable(handle->tx_handle));
    ESP_ERROR_CHECK(i2s_del_channel(handle->tx_handle));
}

esp_err_t MAX98357A_play(MAX98357A_handle_t *handle, const MAX98357A_config_t *config, const int16_t *data, size_t len)
{
    size_t bytes_written = 0;
    gpio_set_level(config->SD_PIN, 1);
    ESP_ERROR_CHECK(i2s_channel_write(handle->tx_handle, data, len, &bytes_written, 1000));
    if (bytes_written != len)
    {
        ESP_LOGE("MAX98357A", "Failed to write all data");
        return ESP_FAIL;
    }
    gpio_set_level(config->SD_PIN, 0);
    return ESP_OK;
}
